// text-encrypt-decrypt/src/App.svelte
<script>
  import InputSection from './lib/InputSection.svelte';
  import CryptoProcessor from './lib/CryptoProcessor.svelte';
  import ResultDisplay from './lib/ResultDisplay.svelte';

  let inputText = '';
  let secretKey = '';
  let mode = 'encrypt';
  let algorithm = 'AES';
  let result = '';
  let error = '';
</script>

<div class="app-container">
  <header class="app-header">
    <h1>🔐 文本加密解密工具</h1>
    <p>支持多种常见加密算法的文本处理工具</p>
  </header>

  <main class="app-main">
    <InputSection
      bind:inputText
      bind:secretKey
      bind:mode
      bind:algorithm
    />

    <CryptoProcessor
      bind:inputText
      bind:secretKey
      bind:mode
      bind:algorithm
      bind:result
      bind:error
    />

    <ResultDisplay
      bind:result
      bind:mode
      bind:algorithm
    />
  </main>

  <footer class="app-footer">
    <p>基于 Svelte + Vite + CryptoJS 构建</p>
  </footer>
</div>

<style>
  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  .app-container {
    min-height: 100vh;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    padding: 40px 20px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  }

  .app-header {
    text-align: center;
    color: white;
    margin-bottom: 40px;
  }

  .app-header h1 {
    font-size: 32px;
    font-weight: 700;
    margin-bottom: 8px;
  }

  .app-header p {
    font-size: 16px;
    opacity: 0.9;
  }

  .app-main {
    max-width: 600px;
    margin: 0 auto;
    background: white;
    padding: 32px;
    border-radius: 16px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.2);
  }

  .app-footer {
    text-align: center;
    color: white;
    margin-top: 32px;
    font-size: 14px;
    opacity: 0.8;
  }
</style>

// puzzle-game-web/client/src/App.vue
<template>
  <div class="app">
    <div class="app-container">
      <header class="header">
        <div class="header-left">
          <span class="logo">🧩</span>
          <span class="title">拼图小游戏</span>
        </div>
        <button class="leaderboard-btn" @click="showLeaderboard = true">
          <span>🏆</span>
          <span>排行榜</span>
        </button>
      </header>
      <main class="main">
        <router-view />
      </main>
    </div>
    <LeaderboardModal
      :visible="showLeaderboard"
      @close="showLeaderboard = false"
    />
  </div>
</template>

<script setup>
import { ref } from 'vue'
import LeaderboardModal from './components/LeaderboardModal.vue'

const showLeaderboard = ref(false)
</script>

<style scoped>
* {
  box-sizing: border-box;
}

.app {
  min-height: 100vh;
  background: #f7f7f7;
  display: flex;
  justify-content: center;
}

.app-container {
  width: 100%;
  max-width: 480px;
  background: #fff;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  box-shadow: 0 0 20px rgba(0,0,0,0.05);
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  background: linear-gradient(135deg, #07c160 0%, #06ad56 100%);
  color: #fff;
  position: sticky;
  top: 0;
  z-index: 100;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 8px;
}

.logo {
  font-size: 24px;
}

.title {
  font-size: 17px;
  font-weight: 600;
}

.leaderboard-btn {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 8px 14px;
  background: rgba(255,255,255,0.2);
  border: none;
  border-radius: 20px;
  color: #fff;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s;
}

.leaderboard-btn:hover {
  background: rgba(255,255,255,0.3);
}

.leaderboard-btn span:first-child {
  font-size: 14px;
}

.main {
  flex: 1;
  padding: 0;
  overflow-y: auto;
}
</style>
